version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres-app
    environment:
      POSTGRES_PASSWORD: "postgres"
      APP_DB_NAME: transaction
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    networks:
      - postgres-network
    healthcheck:
      test: [ "CMD-SHELL", "psql -l | grep transaction | wc -l" ]
      interval: 10s
      timeout: 5s
      retries: 5

  api-service:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge
