version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres-app
    environment:
      POSTGRES_PASSWORD: "postgres"
      APP_DB_NAME: transaction
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    networks:
      - postgres-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --dbname=transaction --username=postgres" ]
      interval: 10s
      timeout: 5s
      retries: 10

  api-service:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres:postgres
    environment:
      - APP_DATABASE_HOST=127.0.0.1
      - APP_DATABASE_USER=postgres
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge
