version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres-app
    environment:
      POSTGRES_PASSWORD: "postgres"
      APP_DB_NAME: transaction
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    networks:
      - postgres-network

  api-service:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge
